{% set name = "napari-timestamper" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napari_timestamper-{{ version }}.tar.gz
  sha256: d4c8aaa32c50ef08a31bc5112ebb49bc250405541d211e8efd86e5f9a745ec5b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42.0.0
    - wheel
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - qtpy
    - napari
    - magicgui

test:
  imports:
    - napari_timestamper
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip
    - pyqt

about:
  home: https://pypi.org/project/napari-timestamper/
  summary: A simple plugin to add a timestamp overlay to napari
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/bgraedel/napari-timestamper

extra:
  recipe-maintainers:
    - bgraedel
